# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-View-GraphViz
version:      0.04
version_from: lib/Catalyst/View/GraphViz.pm
installdirs:  site
requires:
    Catalyst:                      0
    Catalyst::Plugin::SubRequest:  0
    GraphViz:                      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
